include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true

linter:
  rules:
    - directives_ordering
    - prefer_relative_imports
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - unawaited_futures
    - no_runtimeType_toString

plugins:
  riverpod_lint: ^3.1.3
